Repository bot294/GitElinting, pull requests merged in 2024-09, with the labels that each got.

#1 streaming
  app.js
Labels: 1 min review, missing-jira

#2 edit in app.js
  app.js
Labels: 1 min review, missing-jira

#3 edit in app.js
  app.js
Labels: 1 min review, missing-jira

#4 edit in app.js
  app.js
Labels: 1 min review, missing-jira

#6 Re-normalize all files to LF line endings
  eslint.config.mjs
  package-lock.json
  package.json
Labels: 1 min review, missing-clickup

#14 edit in rule
  eslint.config.mjs
Labels: 1 min review, missing-jira

#15 edit
  app.js
Labels: 1 min review, missing-jira

#18 changes
  .github/workflows/gitstream.yml
  .vscode/settings.json
  app.js
Labels: 1 min review, missing-jira

#19 changes
  app.js
Labels: 1 min review, missing-jira

#20 changes
  .vscode/settings.json
Labels: 1 min review, missing-jira

#21 chnages in app.js
  node_modules/.package-lock.json
  node_modules/eslint-formatter-checkstyle/index.d.ts
  node_modules/eslint-formatter-checkstyle/index.js
  node_modules/eslint-formatter-checkstyle/license
  node_modules/eslint-formatter-checkstyle/package.json
  node_modules/eslint-formatter-checkstyle/readme.md
  package-lock.json
  package.json
Labels: missing-jira, 10 min review

#22 Test pr automation
  .vscode/settings.json
  eslint.config.mjs
  new.js
  node_modules/.package-lock.json
  node_modules/@eslint/js/package.json
  node_modules/@eslint/plugin-kit/README.md
  node_modules/@eslint/plugin-kit/dist/cjs/index.cjs
  node_modules/@eslint/plugin-kit/dist/cjs/index.d.cts
  node_modules/@eslint/plugin-kit/dist/esm/index.d.ts
  node_modules/@eslint/plugin-kit/dist/esm/index.js
  node_modules/@eslint/plugin-kit/package.json
  node_modules/eslint/README.md
  node_modules/eslint/lib/config/flat-config-helpers.js
  node_modules/eslint/lib/languages/js/source-code/source-code.js
  node_modules/eslint/lib/linter/linter.js
  node_modules/eslint/lib/linter/vfile.js
  node_modules/eslint/lib/rules/id-length.js
  node_modules/eslint/lib/rules/no-useless-constructor.js
  node_modules/eslint/lib/services/processor-service.js
  node_modules/eslint/lib/shared/types.js
  node_modules/eslint/lib/types/index.d.ts
  node_modules/eslint/lib/types/rules/best-practices.d.ts
  node_modules/eslint/lib/types/rules/ecmascript-6.d.ts
  node_modules/eslint/lib/types/rules/possible-errors.d.ts
  node_modules/eslint/lib/types/rules/stylistic-issues.d.ts
  node_modules/eslint/lib/types/universal.d.ts
  node_modules/eslint/lib/universal.js
  node_modules/eslint/package.json
  package-lock.json
  package.json
Labels: missing-jira, 30 min review

#23 eslint working ok in vs code
  .vscode/settings.json
Labels: 1 min review, missing-jira

#26 Test pr automation
  new.js
Labels: 1 min review, missing-jira

#27 Test pr automation
  eslint.config.mjs
  node_modules/.bin/create-jest
  node_modules/.bin/create-jest.cmd
  node_modules/.bin/create-jest.ps1
  node_modules/.bin/esparse
  node_modules/.bin/esparse.cmd
  node_modules/.bin/esparse.ps1
  node_modules/.bin/esvalidate
  node_modules/.bin/esvalidate.cmd
  node_modules/.bin/esvalidate.ps1
  node_modules/.bin/import-local-fixture
  node_modules/.bin/import-local-fixture.cmd
  node_modules/.bin/import-local-fixture.ps1
  node_modules/.bin/jest
  node_modules/.bin/jest.cmd
  node_modules/.bin/jest.ps1
  node_modules/.bin/json5
  node_modules/.bin/json5.cmd
  node_modules/.bin/json5.ps1
  node_modules/.bin/parser
  node_modules/.bin/parser.cmd
  node_modules/.bin/parser.ps1
Labels: missing-jira, 30 min review

#28 added one function
  new.js
Labels: 1 min review, missing-jira

#30 Added new_fun
  new.js
Labels: 1 min review, missing-jira

#35 Test pr automation
  new.js
Labels: 1 min review, missing-jira

#36 add in new.js
  new.js
Labels: 1 min review, missing-jira

#43 Test pr automation
  new.js
Labels: 1 min review, missing-jira

#46 sub func
  new.js
Labels: 1 min review, missing-jira
